# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_category_name',
            field=models.ManyToManyField(related_name='category_name', to='product.ProductCategory'),
        ),
    ]
