# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201208_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_details',
            field=models.TextField(default='', max_length=250, verbose_name='产品详情'),
        ),
    ]
