# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-14 22:34
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_details',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='产品详情'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_picture',
            field=models.ImageField(upload_to='product_images/', verbose_name='产品图片'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='c_category_thumbnail',
            field=models.ImageField(upload_to='product_category_images/', verbose_name='分类缩略图'),
        ),
    ]
