# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-12 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='', max_length=50, verbose_name='案例名称')),
                ('c_category', models.CharField(default='', max_length=50, verbose_name='案例分类')),
                ('c_introduction', models.CharField(default='', max_length=250, verbose_name='客户介绍')),
                ('c_background', models.CharField(default='', max_length=250, verbose_name='项目背景')),
                ('c_challenge', models.CharField(default='', max_length=250, verbose_name='项目挑战')),
                ('c_details', models.CharField(default='', max_length=250, verbose_name='项目详情')),
                ('c_highlights', models.CharField(default='', max_length=250, verbose_name='项目亮点')),
                ('c_reviews', models.CharField(default='', max_length=250, verbose_name='客户评价')),
                ('c_picture', models.ImageField(upload_to='Stage/Project/CMKJ_website/static/images', verbose_name='项目照片')),
            ],
            options={
                'verbose_name_plural': '案例表',
                'db_table': 'Case',
            },
        ),
    ]
