# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_category',
            field=models.CharField(choices=[('s', '软件'), ('h', '硬件')], default='', max_length=50, verbose_name='案例分类'),
        ),
        migrations.AlterField(
            model_name='case',
            name='c_details',
            field=models.TextField(default='', max_length=250, verbose_name='项目详情'),
        ),
    ]
