# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-14 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0003_auto_20201213_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='c_picture',
            field=models.ImageField(upload_to='project_images/', verbose_name='项目照片'),
        ),
    ]
