# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-30 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_auto_20201214_2234'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='CaseInfo',
        ),
        migrations.AlterModelTable(
            name='caseinfo',
            table='CaseInfo',
        ),
    ]
