# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-12 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(default='', max_length=50, verbose_name='行业服务名称')),
                ('s_category', models.CharField(default='', max_length=50, verbose_name='行业服务分类')),
                ('s_introduction', models.CharField(default='', max_length=250, verbose_name='服务介绍')),
                ('s_details', models.CharField(default='', max_length=250, verbose_name='服务详情')),
            ],
            options={
                'verbose_name_plural': '行业服务表',
                'db_table': 'Service',
            },
        ),
    ]
