# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-12 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_details',
            field=models.TextField(default='', max_length=250, verbose_name='服务详情'),
        ),
    ]
