# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-12-14 22:34
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20201212_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='s_details',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='行业服务详情'),
        ),
    ]
